name: maven
on:
  push:
    branches:
      - main
      - dev/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "hello 11"

  maven-main:
    uses: kopi-sg/dso-workflow/.github/workflows/app-maven-release.yaml@main
    with:
      os_version: "ubuntu-latest"
    secrets: inherit
    needs: test
