name: maven
on:
  push:
    branches:
      - main
      - dev/**

jobs:
  maven-main:
    uses: kopi-sg/dso-workflow/.github/workflows/app-maven-release.yaml@main
    with:
      os_version: "ubuntu-24.04"
    secrets: inherit
